import Foundation
import LocalLLMClientCore

private final class OwnedChatParams: @unchecked Sendable {
    let pointer: UnsafeMutablePointer<llm_chat_params>?

    init(_ pointer: UnsafeMutablePointer<llm_chat_params>?) {
        self.pointer = pointer
    }

    deinit {
        if let pointer {
            free_chat_params(pointer)
        }
    }
}

/// A client for interacting with the Llama models.
///
/// This class provides methods for generating text streams from various inputs,
/// and handles the communication with the underlying Llama model.
public final class LlamaClient: LLMClient {
    private let context: Context
    private let multimodal: MultimodalContext?
    private let messageProcessor: MessageProcessor
    let tools: [AnyLLMTool]
    /// Owned by this client; freed in `deinit`.
    nonisolated(unsafe) private let chatParamsPtr: UnsafeMutablePointer<llm_chat_params>?

    var chatFormat: common_chat_format {
        get_chat_params_format(chatParamsPtr)
    }

    /// Per-request chat-template behavior.
    public struct ChatOptions: Sendable {
        public var enableThinking: Bool

        public init(enableThinking: Bool = true) {
            self.enableThinking = enableThinking
        }

        public static let `default` = ChatOptions()
    }

    /// Initializes a new Llama client.
    ///
    /// - Parameters:
    ///   - url: The URL of the Llama model file.
    ///   - mmprojURL: The URL of the multimodal projector file (optional).
    ///   - parameter: The parameters for the Llama model.
    ///   - messageProcessor: The message processor to use for chat messages (optional).
    ///   - tools: An array of tools that can be used by the model for function calling.
    /// - Throws: An error if the client fails to initialize.
    public init(
        url: URL,
        mmprojURL: URL?,
        parameter: Parameter,
        messageProcessor: MessageProcessor?,
        tools: [any LLMTool] = []
    ) throws {
        context = try Context(url: url, parameter: parameter)
        if let mmprojURL {
            multimodal = try MultimodalContext(url: mmprojURL, context: context, parameter: parameter)
        } else {
            multimodal = nil
        }
        self.messageProcessor = messageProcessor ?? MessageProcessorFactory.createAutoProcessor(chatTemplate: context.model.chatTemplate)
        let wrappedTools = tools.map { AnyLLMTool($0) }
        self.tools = wrappedTools
        self.chatParamsPtr = context.model.buildChatParams(tools: wrappedTools)
    }

    deinit {
        if let chatParamsPtr {
            free_chat_params(chatParamsPtr)
        }
    }

    /// Generates a text stream from the given input.
    ///
    /// - Parameter input: The input to generate text from.
    /// - Returns: A generator that produces text as it's generated by the model.
    /// - Throws: An `LLMError.failedToDecode` error if the input cannot be decoded.
    public func textStream(from input: LLMInput) throws -> Generator {
        try textStream(
            from: input,
            tools: tools,
            options: .default
        )
    }

    /// Generates text using a runtime-provided tool catalog without rebuilding
    /// or reloading the model.
    public func textStream(
        from input: LLMInput,
        tools requestTools: [AnyLLMTool],
        options: ChatOptions = .default
    ) throws -> Generator {
        do {
            switch input.value {
            case .plain(let text):
                context.clear()
                try context.decode(text: text)
            case .chatTemplate(let messages):
                try messageProcessor.process(
                    templateMessages: messages,
                    context: context,
                    multimodal: multimodal,
                    tools: requestTools,
                    additionalContext: ["enable_thinking": options.enableThinking]
                )
            case .chat(let messages):
                try messageProcessor.process(
                    messages: messages,
                    context: context,
                    multimodal: multimodal,
                    tools: requestTools,
                    additionalContext: ["enable_thinking": options.enableThinking]
                )
            }
        } catch {
            context.clear()
            throw LLMError.failedToDecode(reason: error.localizedDescription)
        }

        return Generator(context: context)
    }
    
    /// Streams responses from the input
    /// - Parameter input: The input to process
    /// - Returns: An asynchronous sequence that emits response content (text chunks, tool calls, etc.)
    /// - Throws: An error if generation fails
    public func responseStream(from input: LLMInput) async throws -> AsyncThrowingStream<StreamingChunk, any Error> {
        try await responseStream(
            from: input,
            tools: tools,
            options: .default
        )
    }

    /// Streams responses using a runtime-provided tool catalog.
    public func responseStream(
        from input: LLMInput,
        tools requestTools: [AnyLLMTool],
        options: ChatOptions = .default
    ) async throws -> AsyncThrowingStream<StreamingChunk, any Error> {
        // Create the stream first (this can throw)
        let requestChatParams = OwnedChatParams(
            context.model.buildChatParams(
                tools: requestTools,
                enableThinking: options.enableThinking
            )
        )
        let textStreamGenerator = try textStream(
            from: input,
            tools: requestTools,
            options: options
        )
        let requestFormat = get_chat_params_format(requestChatParams.pointer)

        return AsyncThrowingStream { continuation in
            let processor = StreamingToolCallProcessor(
                startTag: getToolCallStartTag(format: requestFormat),
                endTag: getToolCallEndTag(format: requestFormat)
            )
            
            let producer = Task {
                do {
                    var fullText = ""
                    
                    for try await chunk in textStreamGenerator {
                        fullText += chunk
                        
                        // Process the chunk through the tool call processor
                        if let processedText = processor.processChunk(chunk) {
                            continuation.yield(.text(processedText))
                        }
                    }

                    let parserToolCalls = LlamaToolCallParser.parseToolCalls(
                        from: fullText,
                        chatParams: requestChatParams.pointer
                    ) ?? []
                    var toolCalls = processor.toolCalls + parserToolCalls
                    toolCalls = toolCalls.reduce(into: []) { result, toolCall in
                        if !result.contains(where: {
                            $0.id == toolCall.id
                                || ($0.name == toolCall.name && $0.arguments == toolCall.arguments)
                        }) {
                            result.append(toolCall)
                        }
                    }

                    for toolCall in toolCalls {
                        continuation.yield(.toolCall(toolCall))
                    }

                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in
                producer.cancel()
            }
        }
    }
    
    /// Get the tool call start tag based on chat format
    private func getToolCallStartTag(format: common_chat_format) -> String {
        switch format {
        case COMMON_CHAT_FORMAT_PEG_GEMMA4:
            return "<|tool_call>"
        default:
            return "<tool_call>"
        }
    }

    /// Get the tool call end tag based on chat format
    private func getToolCallEndTag(format: common_chat_format) -> String {
        switch format {
        case COMMON_CHAT_FORMAT_PEG_GEMMA4:
            return "<tool_call|>"
        default:
            return "</tool_call>"
        }
    }
    
    /// Pauses any ongoing text generation
    public func pauseGeneration() async {
        await context.pauseHandler.pause()
    }
    
    /// Resumes previously paused text generation
    public func resumeGeneration() async {
        await context.pauseHandler.resume()
    }
    
    /// Whether the generation is currently paused
    public var isGenerationPaused: Bool {
        get async {
            await context.pauseHandler.isPaused
        }
    }
}

public extension LocalLLMClient {
    /// Creates a new Llama client.
    ///
    /// This is a factory method for creating `LlamaClient` instances.
    ///
    /// - Parameters:
    ///   - url: The URL of the Llama model file.
    ///   - mmprojURL: The URL of the multimodal projector file (optional).
    ///   - parameter: The parameters for the Llama model. Defaults to `.default`.
    ///   - messageProcessor: The message processor to use for chat messages (optional).
    ///   - tools: An array of tools that can be used by the model for function calling.
    ///   - verbose: A Boolean value indicating whether to enable verbose logging. Defaults to `false`.
    /// - Returns: A new `LlamaClient` instance.
    /// - Throws: An error if the client fails to initialize.
    static func llama(
        url: URL,
        mmprojURL: URL? = nil,
        parameter: LlamaClient.Parameter = .default,
        messageProcessor: MessageProcessor? = nil,
        tools: [any LLMTool] = []
    ) async throws -> LlamaClient {
        setLlamaVerbose(parameter.options.verbose)
        return try LlamaClient(
            url: url,
            mmprojURL: mmprojURL,
            parameter: parameter,
            messageProcessor: messageProcessor,
            tools: tools
        )
    }
}

#if DEBUG
extension LlamaClient {
    var _context: Context {
        context
    }

    var _multimodal: MultimodalContext? {
        multimodal
    }
}
#endif
